# Development recurring tasks
development:
  heartbeat_monitor:
    class: HeartbeatMonitorJob
    schedule: every minute

# Production-only tasks
production:
  heartbeat_monitor:
    class: HeartbeatMonitorJob
    schedule: every minute
